### ISSUE TITLE
Define some features and techniques in more detail

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#137]
Instead of a combat document, I decided to write all my questions in a single place, allowing us to have a more in depth discussion regarding each item. The questions are divided in categories, and are not ordered in any way (so the first questions are not specifically the most important ones, just the ones I thought about first while writing).

# Combat
- [x] Will guns fire fast-moving projectiles (like they currently do), or is it better to implement RayCasts to some guns, making the "projectile" travel instantly and hit it's target? If we use a RayCast, we can play a short animation of a blurry projectile flying towards the target to make it clear what caused the damage. Both options have pros and cons:
   - Physical Projectiles:
      - Are more realistic, since each projectile is a physical object that can collide against other objects in the game
      - Can be used for projectiles of different speeds and flying trajectories, since the projectiles are moved using physics simulation. So things like gravity, bounce, reflection, etc., are all possible
      - They are WAAAAY more expensive to calculate than RayCasts, since they are actually moving and detecting collisions on every frame. A known issue with every engine (even Unreal) is that if a physical projectile is moving too fast, it may move inside other objects before triggering a collision, or in worst cases, may go through an object entirely, since the projectile has not collided yet in one frame, but has moved past the object in the very next frame. There are ways to tell Godot to increase the collision efficiency, avoiding most of these issues at the cost of some performance (because more time is dedicated to calculating collisions than normal)
   - RayCasts (or HitScans, as they are usually called):
      - Are less realistic, since instead of actually firing a projectile, the game will fire a Ray at the specified direction, detecting collisions along the way. This all happens in a single frame, so the "projectile" hits the targets instantly, and it's trajectory cannot be modified (since the Ray is a straight line)
      - Would require some sort of very fast and blurry animation to show the "projectile" flying towards it's target. Otherwise, the gun will play it's firing animation and the target will take damage, without anything happening between them. Of course, this is also an option. Earth Worm Jim 2 had a gun that worked like that, hitting enemies instantly, and the only indication of where the bullets were hitting was the dust flying off from whatever was hit
      - They are fast. Like, insanely fast. Since there are no physics simulation, firing a Ray and detecting what was hit happens in a single frame, so we can make guns that turn the game into a bullet hell with practically no performance hit
   - We can, of course, use both approaches, using RayCasts when possible, but implementing physical projectiles for guns that shoot things that require a more detailed implementation (like lobbing bombs, tracking a target, etc.). If the projectile is not moving too fast and the gun doesn't fire too many at once, the performance of the game should remain good.
- [x] Will enemies use a mix of melee and ranged attacks, or will they be limited to only one of the two?
- [x] What's the expected Time To Kill? This is the time it takes to kill an enemy or to die to one. Since Hestmor has 3 HP, I'm thinking most characters can be killed rather quickly, so I think it's better to think about this as soon as possible.
- [x] Will the guns affect Hestmor's speed or other stats? For example, holding a big gun will slow her down, but maybe offer some other benefits.
- [x] Will the damage have types, like Fire, Poison, etc?
- [x] When taking damage, will Hestmor be knocked back a little, like in the old Castlevania games?
- [x] Will the player be able to sneak up on some enemies before the combat starts, or are the enemies aware of Hestmor as soon as they enter the screen?
- [x] After leaving an enemy's line of sight, will that enemy lose the player and try to find them again, or are the enemies always aware of the player's position once combat starts?
- [x] Will Hestmor be able to be damaged while Executing an enemy?
- [x] The melee attack consists of a single swipe, or can Hestmor perform some combos?
- [x] Will enemies be able to damage one another? If yes, is this tied to only specific attacks, or any projectile fired can harm any creature hit by it?

# Gameplay
- [x] Will the player be able to remap the controls? If yes, we need to define which actions will be able to be edited
- [x] Will the player be able to adjust some settings to suit their play style, like deciding between having to hold the run key to run, or being able to run by just tapping it once?
- [x] Will there be any NPC that's not an enemy that's able to be killed? For now, I'm assuming every NPC is hostile and can be damaged.
- [x] Now that we have a crawling animation, will the player be able to move while Crouched, or is the animation exclusive to moving while on a steep slope?
- [x] I noticed how the script separates the level in "rooms". Will this look like old Megaman and Clastlevanis titles, with the screen scrolling once the player reaches it's edge, or is it more like Megaman X, with the screen scrolling while the player moves?
- [x] When playing with a controller, will Hestmor gain speed while the analog stick is being moved, or will she snap to her regular speed once a certain threshold is passed? For now, Hestmor's speed depends on how much the analog stick was moved
- [x] Will the new melee attack move Hestmor once started? I know some of them are basically the regular attack but with slight variations, but the Pounce, for example, will lock Hestmor in a forwards movement while it's being executed?
- [x] Will the melee attacks snap to enemies to make it easier to hit? For example, if an attack is executed while a little bit too close or too far away from an enemy, Hestmor can lock on the enemy and perform the attack from the correct distance

# Graphics
- [x] Hestmor will actually hold the guns she's using, right? This is a little complex to implement, since we'll need sprites for aiming in different directions, as well as aiming while performing other actions (like jumping, falling, etc.). Usually 2 sprites will be used in cases like this, one for the upper body, and one for the lower body, so we can have the arms and legs animated correctly without having to actually draw every variation of every sprite. The other option, and the one usually used, is to have the character's hand disconnected from their body, and the hand floats around the character while holding the gun, but this approach is more cartoonish and probably will not look right.
![image](https://github.com/Team-Awkward-Smile/Epilogue/assets/49737868/af6814ba-ca1d-459b-81dc-6560d47296fb)
- [x] Will the Crawling animation be used even when going down a steep slope, or only when going up?

**Comment by Pseudo-64** [comment]
@vitormaduro 

1)	Combat Questions Answered + Extras

•	Regular Enemies will – A) Shoot You With Projectile, and B) Use Melee. The usage will be depended on how far the enemy is from you. If the enemy is far away, it will use its projectile, and if its close then it will use Melee.

•	Regular Enemies will also have a third attack – Glory State Attack. Basically, when they first go into glory kill, they start blinking and are in a stunned state for a while (seconds many vary for said stun state from enemy to enemy, depending on weight and attack damage categories for balance), and if you don't kill them in said stun state, they'll get up to attack while still blinking. NO HEALTH WOULD BE RESTORED FOR THEM. Their health is still down to the glory kill parameter and they would still be blinking like they do in the glory kill state, but they would just get up to attack their special attack, which could either be melee or projectile, depending on the enemy, and said attack will do twice the damage of their regular melee or projectile attack. 

•	Upon seeing you enemies try to get slightly closer to you. Certain enemies like Icarsia will even try to chase you, while some like the TUC may try to maintain their distance to the best of the possiblility. But if they aren't standing on an elevated platform on a vertical distance, and are standing on a horizontal distance, they will definitely try to get as closer as possible. 

•	If an enemy is on a vertical platform above you, even if that means he is just cms away, he will perform a projectile. 

•	The platforms will not have any collision to bullets, on the ground, ceilings, and walls do, like classic contra games. 

•	The environmental enemies will mostly have one form of attack, as they act more as traps than actual regular enemies. They don't enter glory kill state or have any weapons to give, and most die in one or two bullets when hit at the sweet spot. 

•	The expected time to kill will depend from enemy to enemy to determine, but yeah, the atmost an enemy may take is seven bullets to kill. Again, this depends on the enemy vs. the gun type, but at most an enemy may take a player to kill should be around 6-8 seconds of good shots with a gun that is weak against said enemy. 

•	  The Guns will use fast moving projectile. RayCast may play messy, and unique projectiles may give uniqueness to guns. 

•	The Weight Of Gun will not have any effect on Hestmor's speed or stats.

•	That's a thing I have been combating a little with myself, but perhaps yes and no. If you are talking about to the enemies, then I think I have already explained that its gun-enemy relation, not an element-enemy relation as each gun only has one element. However, in case of enemies getting into traps like getting hit by a fire from a trap, then they would have the same amount of damage as in from the gun of that element. Like if say the fire gun is a flamethrower, and exposure to 1.1 seconds of fire killed the enemy, then if the enemy is exposed to the fire for same amount of time, then it would die similarly. 

•	In case of damage types in relation to Hestmor, then every attack, that is not specialized attack from the glory kill state, does a one HP damage to her health. Get the amount of health times you have, and you'll die. There is one status after effect though, and that is poison. This is not in relation to any of the regular enemy, but the environmental enemy. If said environmental enemy gets a hit on you with a poison projectile, like moss plant of guwama, then your health will keep draining, until you have killed them. Moss plants of guwama die from everything except the water gun in one hit, so it shouldn't be a problem in terms of timing. 

•	At first I wasn't thinking this, but yeah, now that I think if Hestmor gets hit, then she will have a knockback. 

•	When growling, Enemies will have a "get the fuck away" from her meter, where they may not try to get close to Hestmor. So for example of Icarasia, growling 1 will keep them away for 3 seconds, growling 2 for 5 seconds, and growling 3 for 10 seconds (just example). They will also have a "No Attack" period, that will be smaller than the "get the fuck away" from her period, in which they won't attempt an attack on Hestmor, even with a projectile. Both period of "get the fuck away from her" and "No Attack" will be given separately to depending on the enemy and defined on an excel sheet later on. 

•	Bosses will have vision cones, like Foki-Umia and Spider-mother, in certain chase scenarios. However, I am half-half on the regular enemies. For now, with regular enemies they will attack as soon as you enter, and I think for a faster pacing that maybe better. For there is no point where you will have to sneak away from regular enemies. 

•	If the player someone manages to runaway from the enemy but is still in the same room, then that previous enemy may try to chase you under the confinement of said room. Once a room is exited, they will not follow 

•	Yes, Hestmor will be able to be damaged when try to execute a glory kill. That is where the "fast glory kill" and "slow glory 
kill" idea comes to play. For if the player, is choosing slow glory kill they get more ammo but are more exposed to enemy attack for long. Vice versa for the fast glory kill. 

•	If Hestmor gets hit anytime during executing a glory kill, she will get a knock back, resulting in her having to do the glory kill all over again. 

•	No combos. Just one single swipe. Though I may like to keep the combo idea for future entries or different games, for now it’s a single swipe to keep things more simpler. Combos may become messy.

**Comment by Pseudo-64** [comment]
@vitormaduro 

2)	Gameplay Questions Answered + Extras

•	Yes, the player maybe be able to remap controls. Movement and Combat keys can be remapped to their heart's desire. The only UI button that player can remap is the Pause Button. Other UI buttons and controls are fixed. 

•	Yes, the player will be able to adjust some settings. The major and obvious one being Mouse Sensitivity. About the run button. First of all when starting the game and kicking in a new game or new game+, the game will ask you about your playstyle choice. If the player is just on computer, they will get choice between Keyboard & Mouse (Modern) or Just Keyboard (Retro). If a control input is detected, then it will ask for two more options – Analog (Modern) or D-pad (Retro). When choosing any one of them, the game will pop a message, "the controls and toggles have now been mapped for optimal play with your playstyle and device choice– to change it go to settings", which means that in case the player has by any means remap any controls, the control will now reset to our definitive layout in context to said playstyle. For example, while every other playstyle will require you to hold the run button, the retro controller will have you toggle run with select button. The player will be given choice to change said things on settings, including their run choice of either it being toggle or hold, like if you are mad enough, you can make run to hold in retro controller mode. Meaning that if you are going by default controls provided, then you will have to press select with d-pad to run. Maybe we can even make a special achievement for the idiots who decide to use HOLD RUN with retro controller mode. 

•	Crawling animation is up-slope only and that after a certain angle. Hestmor will simple walk when downslope. In case of stairs, we may need a separate walking up and walking down animation. 

•	No, the player will not be able to crouch and move. Crouch is  a dodge-move, not a movement. 


•	Hestmor will always remain at the centre of the screen, so it is Megaman X camera that we are following. In that, the screen will keep scrolling. The current branches you have provided seems to follow that, so that is good, as we don't need to change anything in terms of camera. The rooms in a sense, define the checkpoints and saving points. When entering a new room, the player will have a checkpoint and an autosave (in New Game and New Game+), and any enemy that was chasing them in the previous room, will not be following her.

**Comment by Pseudo-64** [comment]
@vitormaduro 3)	Graphics questions answered 
•	This one needs some discussion with the artist. Lorenzo (Skaers) suggested that we go with each weapon almost becoming an ornament on Hestmor's naked skin. So, chances are we may need to make all sprites with each weapon from scratch. But I obviously need to find more optimal way around this, so I will have it on discussion with mint and other artists on a vc on August 24 (cannot do August 17 since its my birthday). I am keeping the box on this unchecked, because it may still need answering. 

•	I think I kind of answered it, but again, the crawling animation only plays up-slope or in tight spaces. During both of which you will just be pressing forward. Crouch and crawl is not an option. You won't be crawling downwards…because where's the fun in that.

**Comment by Pseudo-64** [comment]
@vitormaduro oops, forgot to answer one more question. 

About the NPC that is killable thing. 

Okay, so you already know that Tupois is consumable, since you can press growl and eat them. 

And if you are upto date with the finale of the script, yes, the NPC of Priests of Zagara, both new and old, are killable. They just run away like chicken and can be killed in one hit by anyone, and will splatter huge, ridiculous, amounts of blood all over the place.

**Comment by Pseudo-64** [comment]
@vitormaduro while monster in damage is possible, aka, if a monster gets in way of another monster's projectile, it may damage the monster. Monster in-fighting is not a thing. Since due to lore reasons, all monsters are under mind control, they will not try to fight each other, and will keep their focus on hestmor.

**Comment by Pseudo-64** [comment]
@vitormaduro Gameplay new questions, answers. 

1) No. To keep the experience more unified across gamepads and pc, hestmor will only run when the run button is held, and would have a unified scheme with both control schemes to keep a sense of consistency. 

2) The idle and walking attacks will not mess with Hestmor's momentum, but the run attack will provide Hestmor with a slight slide afterwards. I have sent mint the details on that. About the pouncing, I think a similar case can be made of it locking the player in a forward momentum, similar to the run attack. 

3) No, because I feel that lock-on system can bring its own set of issues, and I feel like a little challenge for the player is never a bad thing. Maybe for any future projects I might consider lock-on, but for now, no.

**Comment by Pseudo-64** [comment]
@vitormaduro I think the remaining feature question of "Will Hestmor hold the gun" is kind of answered if you were present there for the last voice chat. As obviously mentioned, it maybe ornamental as to give Hestmor a different appearance. Since technically that is answered, I am closing this issue (if need be, you can re-open it), and creating a separate new issue regarding brainstorming for the reducing the amount of work for animation and to be able to do them swiftly, which is obviously our current big issue at hand, as a big fear is the amount of animation and re-animation it may take to re-do movements to fit the weapon at hand.
