### ISSUE TITLE
Define how jumping works

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#150]
- How fast will Hestmor leave the ground after the button is pressed?
- Can Hestmor move while jumping?
- Can Hestmor choose between a high jump and a long jump (maybe by pressing forwards while the jump starts)?
- Will Hestmor deal bonus damage when attacking during a jump/pounce?

**Comment by Pseudo-64** [comment]
@vitormaduro So here are the answers regarding said questions: 

Answer 1: I think this one would need testing, but from the player feedback I could gather, we need to make the jump much more quicker. So, obviously, we need to mitigate any feeling of any input delay. Let's see if either removing some frames of animation, or maybe just making the input read from the controller/keyboard faster will help the case. 

Answer 2: No. Though Hestmor can move during some falling segments that may make use of parallax scrolling, during jump, it is not possible. 

Answer 3: So, I thought about this and came to the optimal solution. I don't think providing player choice in this would be good, instead I would like to make this related to the movement before the jump is executed. Basically, A) If the player is walking then the jump would be a low jump, and B) if the player is running before the jump, then the player would do the long jump. In fact now that as I type this, I realize that we can also provide a "same place" jump/hop to players if they are standing idle. I will assign issue regarding to commence an animation, but yeah, in case of walking and running, walking would lead to low jump and running will lead to high jump. I think in those two cases, we may not need to assign any new animations, so it should be fine. 

Answer 4: Hmmm...you know what, why the fuck not. In fact, since we are assigning different attack animations for different movements (Idle, walking, jumping, falling, and running), we can assign different attack outputs for all of them. The riskier the movement, the greater the attack damage. This will/may create a risk-reward system for the players, where let's say, running is obviously much more dangerous as you are less likely to dodge attacks quickly, but the resulting damage will be more satisfying.

**Comment by Pseudo-64** [comment]
@vitormaduro these questions were answered, do you want me to close the issue, or do you want to keep it open until either you transport the answers in wiki for you to keep track of or those things are actually implemented.

**Comment by vitormaduro** [comment]
I'll close it, thank you for reminding me
