### ISSUE TITLE
Read The Currently Defined Mechanical Workings - Comment Back With Thoughts, And Feel Free To Make State Machine Diagrams For Individual Enemies If Need Be

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#206]
https://github.com/Team-Awkward-Smile/Epilogue/wiki/Mechanical-Workings-Of-Individual-Enemies

- [x] Icarasia - https://github.com/Team-Awkward-Smile/Epilogue/wiki/Mechanical-Workings-Of-Individual-Enemies#icarsia

- [x] Vafa' Keleth - https://github.com/Team-Awkward-Smile/Epilogue/wiki/Mechanical-Workings-Of-Individual-Enemies#vafa-keleth

- [x] Terra Bischem - https://github.com/Team-Awkward-Smile/Epilogue/wiki/Mechanical-Workings-Of-Individual-Enemies#terra-bischem

- [x] Moss Plant Of Guwama - https://github.com/Team-Awkward-Smile/Epilogue/wiki/Mechanical-Workings-Of-Individual-Enemies#moss-plant-of-guwama

**Comment by vitormaduro** [comment]
NPCs work very differently from the Player, because they need to constantly run their AI logic, so assigning one single State to them at a time was not working very well. Instead, their States are used to control animations and other variables, with one of them being the "main" State that is used most of the time. Because of that, creating a diagram of their State Machines would be a little useless...

Anyway, here are my thoughts:
- Icarasia:
   - Everything seems very doable (I specially liked the suggestion of not doing the hunt scene dynamically), but I still need to check how to properly do the path-finding for flying enemies. For now, the Navigation polygon is tied to the Tile Set, so NPCs need to be in contact with the ground to move around
   - The whole "if near a ceiling/if near the ground" may require some testing
- Vafa'Keleth
   - No comments here. I'm already experimenting with Rob the option to perform different attacks depending on Hestmor's position
- Terra Bischem
   - The animation of the eye staring at Hestmor will need to be done by code. Not hard to do, we just need to rotate the sprite until the pupil is pointing to the correct direction, but we may need to do some tests to make sure it looks polished enough
   - The logic to define it's appearance may be manual. Instead of dynamically determining what form to use, each Terra Bichem can have a property editable from the Editor to set it's form
   - I've been thinking about projectile reflection already, but for now there's no way do to that. To make it look right, this part will require some attention
   - Honestly, I think it would be easier to treat each form as a separate enemy. No promises for now, but they work so differently from one another that writing all of the code at one place may clutter the script (unless we decide they can change form, then it all needs to be part of the same NPC)
- Moss Plant of Guwama
   - Everything is fine, except for the bouncing projectile (as mentioned earlier). When attacking the projectile, though, would it just change direction, or would it fly straight towards the plant?

**Comment by Pseudo-64** [comment]
@vitormaduro in case of moss plant, I was thinking of having some sort of physics simulation for the projectile. So that it bounces to place depending on how you hit. To better explain it, think of it as a sideways pong or block. And the player will have to redirect it towards the enemy.

**Comment by vitormaduro** [comment]
Ok, no problem then

**Comment by vitormaduro** [comment]
Update: I refactored Rob's code to use a regular State Machine just like Bob. I'll sketch some diagrams later of how each enemy's State Machine may look like
