### ISSUE TITLE
Decide if the jumps will reach the same height

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#243]
For now, since all 3 types of jump have the same vertical, they all reach the same height. The only difference between them is the horizontal distance traveled

**Comment by Pseudo-64** [comment]
@vitormaduro I think I answered this earlier or not, or i just missed the existence of this issue entirely becoz it got buried a little. 
But I think we should go like this: 

* Vertical Jump: Is the highest you can reach height wise i guess, since the entire point is Hestmor trying to jump upwards. No distance traveled. 
* Short Jump: Lowest in terms of height. Medium in terms of distance. (have some doubts, read below)  
* Long Jump: Highest in terms of distance, medium in terms of height (basically higher than short jump but lower than vertical jump?)

is this okay, or should we go with long distance but low height with long jump. I see two trajectories when it comes to the short jump and long jump. 

Trajectory A: Short jump reaches more height, but again, the distance isn't that satisfactory, while long jump reaches more distance but the height falls short. 

Trajectory B: Short jump reaches less height and distance, and long jump reaches higher in both cases. 

Either way, vertical jump is the highest when it comes to height, and lowest when it comes to distance.

**Comment by Pseudo-64** [comment]
@vitormaduro to better illustrate the two trajectories i am thinking, i drew them. 

TRAJECTORY A: Short jump leads to more height but less distance. 


![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/0b628056-4cae-49ac-96eb-d437ce78d1e4)


TRAJECTORY B: Short jump leads to less height and less distance. 



![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/4728f4c7-83d4-4cef-9543-26873167ed1a)

**Comment by vitormaduro** [comment]
I was playing around with some changes and this was one of them. Branch #261 will be published with different jump velocities for us to test, so I'm closing this issue
