### ISSUE TITLE
Make sample walking sfx on rocky cave like grounds

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#321]
So, our main character looks like this. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/ebd6faaa-f29f-4325-b0e4-d6525e3b04cb)

And its walking animation look like this (current test sprite we made for mechanics testing)

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/573c892a-5fe4-47cd-8a5d-af1b1eff3fdd)

So, I want to test how her walking may sound like in a rocky cave like this, (current placeholder concept image from castlevania and real life rock caves): 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/427563bd-858a-4e00-b70d-ea53fb624169)

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/b27a5119-2859-48ce-8fcd-ba4b3a61def7)

If you have any confusion or further clarifications, feel free to contact me.

**Comment by vitormaduro** [comment]
Please note that in order to allow the SFX to work correctly when the player starts and stops moving, instead of creating one audio file with the character moving, you should instead create multiple files, each one with a single SFX. For example, if the final audio contains 3 versions of the "stepping on stone while running" audio, then 3 separate files are to be created, each one containing only their respective audio without pauses.

I know this is more complex, but having access to these "pieces" allow us to create a more seamless and natural result, where the SFX in synced to the animation, regardless of it's speed

**Comment by davidebunino** [comment]
[Rock Steps.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13835185/Rock.Steps.zip)
@Pseudo-64 @vitormaduro

**Comment by Pseudo-64** [comment]
@vitormaduro if you implement the rock steps for testing, try to keep the volume of this particular SFX a little lower than any other, because on full volume it sounds screechy. It needs to be implemented more subtly, so keep the volume of this low.
