### ISSUE TITLE
Create A Prototypical Control Layout And Test It

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#68]
@vitormaduro Layout Has been uploaded on wiki. Waiting Testing implementation. 
https://github.com/Team-Awkward-Smile/Epilogue/wiki/Control-Layout#epilogue-prototypical-control-layout

**Comment by vitormaduro** [comment]
- Modern
- [x] Walking with A and D
- [x] Walking with Left Analog
- [x] Running with Shift + A and Shift + D
- [x] Running with L3 + Left Analog
- [x] Crouching with S
- [x] Crouching with Left Analog (down)
- [x] Jumping with Space
- [x] Jumping with Cross
- [x] Sliding with Left Ctrl while moving
- [x] Sliding with Circle while moving 
- [x] Sliding with Left Ctrl while stationary
- [x] Sliding with Circle while stationary
- [x] Cancelling slide with W
- [x] Cancelling slide with Left Analog (up)
- [x] Attacking with Mouse 1
- [x] Attacking with R1
- [x] Aim in 8 directions with the mouse
- [x] Aim in 8 directions with Right Analog
- Retro
- [x] Walking with Left Arrow and Right Arrow
- [x] Walking with D-Pad Left and D-Pad Right
- [x] Running with Shift + A and Shift + D
- [x] Toggle between Run and Walk with Select
- [x] Crouching with Down Arrow
- [x] Crouching with D-Pad Down
- [x] Jumping with Z
- [x] Jumping with Cross
- [x] Sliding with Space while moving
- [x] Sliding with Circle while moving 
- [x] Sliding with Space while stationary
- [x] Sliding with Circle while stationary
- [x] Cancelling slide with Up Arrow
- [x] Cancelling slide with D-Pad Up
- [x] Attacking with Left Ctrl
- [x] Attacking with Square
- [x] Aim in 8 directions with WASD
- [x] Aim in 8 directions with L1, R1, L2, and R2

I'm waiting for more animations to test the other actions

**Comment by vitormaduro** [comment]
Since this is just a basic implementation of the remaining actions, there are a few issues I'm already aware of:

- When pausing for the first time, the first slider will be selected. However, unpausing the game and pausing again will not focus of any element of the UI
- The console will still allow the game to react to the keys being pressed, so typing on it will make Bob do weird things
- The Glory Kill system is still super basic and need a ton of work to look good
- Growling and Dropping/Picking Up a gun are not exclusive, so the Growl animation will always play
- Even when a gun is "equipped", the melee animation will always play. A message will tell, however, the direction the shot was supposed to be shot, so this just need a visual improvement

**Comment by Pseudo-64** [comment]
@vitormaduro Certain control layouts have been remapped after testing. Ticks have been removed for implementation.
